
db.hoteles.insertMany([
  {"_id": 1, "nombre": "Burj Al Arab", "ubicacion": "Emiratos Árabes Unidos", "calificacion": 5, "descripcion": "Un hotel de lujo icónico, diseñado como una vela gigante.", "capacidad_maxima_por_habitacion": 2, "area_m2": 28000, "tarifa": 1500, "numero_pisos": 28, "tamano_habitaciones_m2": 70, "ingresos_mensuales": 60000000},
  {"_id": 2, "nombre": "Pestana CR7 Gran Vía", "ubicacion": "España", "calificacion": 4.5, "descripcion": "Hotel de lujo inspirado en el futbolista Cristiano Ronaldo, conocido por su diseño moderno y servicios de alta calidad.", "capacidad_maxima_por_habitacion": 3, "area_m2": 15000, "tarifa": 250, "numero_pisos": 10, "tamano_habitaciones_m2": 45, "ingresos_mensuales": 25000000},
  {"_id": 3, "nombre": "The Savoy", "ubicacion": "Reino Unido", "calificacion": 5, "descripcion": "Hotel histórico con un ambiente elegante y vistas al río.", "capacidad_maxima_por_habitacion": 2, "area_m2": 10000, "tarifa": 800, "numero_pisos": 6, "tamano_habitaciones_m2": 40, "ingresos_mensuales": 25000000},
  {"_id": 4, "nombre": "Hotel de Crillon", "ubicacion": "Francia", "calificacion": 5, "descripcion": "Un hotel clásico en la Place de la Concorde, conocido por su lujo.", "capacidad_maxima_por_habitacion": 2, "area_m2": 11000, "tarifa": 1200, "numero_pisos": 5, "tamano_habitaciones_m2": 55, "ingresos_mensuales": 27000000},
  {"_id": 5, "nombre": "The St. Regis", "ubicacion": "Estados Unidos", "calificacion": 5, "descripcion": "Conocido por su elegancia y un servicio de mayordomo personalizado.", "capacidad_maxima_por_habitacion": 2, "area_m2": 15000, "tarifa": 1000, "numero_pisos": 29, "tamano_habitaciones_m2": 60, "ingresos_mensuales": 42000000},
  {"_id": 6, "nombre": "The Oberoi", "ubicacion": "India", "calificacion": 5, "descripcion": "Un hotel de lujo que combina la tradición india con la modernidad.", "capacidad_maxima_por_habitacion": 2, "area_m2": 22000, "tarifa": 800, "numero_pisos": 30, "tamano_habitaciones_m2": 55, "ingresos_mensuales": 35000000},
  {"_id": 7, "nombre": "The Peninsula", "ubicacion": "China", "calificacion": 5, "descripcion": "Conocido por su servicio excepcional y vistas espectaculares de la ciudad.", "capacidad_maxima_por_habitacion": 2, "area_m2": 20000, "tarifa": 1200, "numero_pisos": 30, "tamano_habitaciones_m2": 60, "ingresos_mensuales": 40000000},
  {"_id": 8, "nombre": "Raffles", "ubicacion": "Singapur", "calificacion": 5, "descripcion": "Un hotel colonial icónico, famoso por su historia y su servicio de alta gama.", "capacidad_maxima_por_habitacion": 2, "area_m2": 25000, "tarifa": 1200, "numero_pisos": 5, "tamano_habitaciones_m2": 70, "ingresos_mensuales": 45000000},
  {"_id": 9, "nombre": "The Dorchester", "ubicacion": "Reino Unido", "calificacion": 5, "descripcion": "Hotel de lujo con un servicio excepcional y un famoso spa.", "capacidad_maxima_por_habitacion": 2, "area_m2": 20000, "tarifa": 900, "numero_pisos": 5, "tamano_habitaciones_m2": 65, "ingresos_mensuales": 37000000},
  {"_id": 10, "nombre": "The Langham", "ubicacion": "Estados Unidos", "calificacion": 5, "descripcion": "Hotel de lujo con una historia rica y una atención al detalle excepcional.", "capacidad_maxima_por_habitacion": 2, "area_m2": 15000, "tarifa": 800, "numero_pisos": 13, "tamano_habitaciones_m2": 50, "ingresos_mensuales": 30000000},
  {"_id": 11, "nombre": "Shangri-La Hotel", "ubicacion": "Australia", "calificacion": 5, "descripcion": "Hotel de lujo con impresionantes vistas de la Ópera de Sídney.", "capacidad_maxima_por_habitacion": 3, "area_m2": 18000, "tarifa": 950, "numero_pisos": 20, "tamano_habitaciones_m2": 55, "ingresos_mensuales": 35000000},
  {"_id": 12, "nombre": "Hotel Negresco", "ubicacion": "Francia", "calificacion": 5, "descripcion": "Un hotel histórico frente al mar, famoso por su arquitectura y arte.", "capacidad_maxima_por_habitacion": 2, "area_m2": 12000, "tarifa": 800, "numero_pisos": 6, "tamano_habitaciones_m2": 45, "ingresos_mensuales": 25000000},
  {"_id": 13, "nombre": "The Carlyle", "ubicacion": "Estados Unidos", "calificacion": 5, "descripcion": "Conocido por su elegancia y su ambiente exclusivo, ubicado en el Upper East Side.", "capacidad_maxima_por_habitacion": 2, "area_m2": 10000, "tarifa": 800, "numero_pisos": 34, "tamano_habitaciones_m2": 50, "ingresos_mensuales": 30000000},
  {"_id": 14, "nombre": "Hotel Adlon", "ubicacion": "Alemania", "calificacion": 5, "descripcion": "Hotel de lujo con vistas a la Puerta de Brandeburgo, conocido por su servicio impecable.", "capacidad_maxima_por_habitacion": 2, "area_m2": 15000, "tarifa": 700, "numero_pisos": 6, "tamano_habitaciones_m2": 45, "ingresos_mensuales": 30000000},
  {"_id": 15, "nombre": "The Ritz Paris", "ubicacion": "Francia", "calificacion": 5, "descripcion": "Hotel icónico en el corazón de París, conocido por su lujo y elegancia.", "capacidad_maxima_por_habitacion": 2, "area_m2": 15000, "tarifa": 1000, "numero_pisos": 6, "tamano_habitaciones_m2": 50, "ingresos_mensuales": 30000000},
  {"_id": 16, "nombre": "The Four Seasons", "ubicacion": "Estados Unidos", "calificacion": 5, "descripcion": "Famoso por su servicio y comodidades de lujo en Beverly Hills.", "capacidad_maxima_por_habitacion": 2, "area_m2": 20000, "tarifa": 1000, "numero_pisos": 5, "tamano_habitaciones_m2": 65, "ingresos_mensuales": 40000000},
  {"_id": 17, "nombre": "The Biltmore", "ubicacion": "Estados Unidos", "calificacion": 5, "descripcion": "Hotel de lujo con una rica historia y un hermoso jardín.", "capacidad_maxima_por_habitacion": 2, "area_m2": 10000, "tarifa": 800, "numero_pisos": 4, "tamano_habitaciones_m2": 45, "ingresos_mensuales": 20000000},
  {"_id": 18, "nombre": "The Sukhothai", "ubicacion": "Tailandia", "calificacion": 5, "descripcion": "Famoso por su servicio y su ambiente sereno en el corazón de Bangkok.", "capacidad_maxima_por_habitacion": 2, "area_m2": 18000, "tarifa": 700, "numero_pisos": 8, "tamano_habitaciones_m2": 55, "ingresos_mensuales": 35000000},
  {"_id": 19, "nombre": "InterContinental", "ubicacion": "China", "calificacion": 5, "descripcion": "Hotel de lujo con vistas panorámicas y comodidades excepcionales.", "capacidad_maxima_por_habitacion": 2, "area_m2": 20000, "tarifa": 900, "numero_pisos": 30, "tamano_habitaciones_m2": 60, "ingresos_mensuales": 40000000},
  {"_id": 20, "nombre": "Palace Hotel", "ubicacion": "Japón", "calificacion": 5, "descripcion": "Conocido por su servicio impecable y vistas al Palacio Imperial.", "capacidad_maxima_por_habitacion": 2, "area_m2": 18000, "tarifa": 850, "numero_pisos": 20, "tamano_habitaciones_m2": 60, "ingresos_mensuales": 35000000},
  {"_id": 21, "nombre": "The Beverly Hills Hotel", "ubicacion": "Estados Unidos", "calificacion": 5, "descripcion": "Famoso por su icónica fachada rosa y su glamour.", "capacidad_maxima_por_habitacion": 2, "area_m2": 15000, "tarifa": 900, "numero_pisos": 6, "tamano_habitaciones_m2": 60, "ingresos_mensuales": 32000000},
  {"_id": 22, "nombre": "Waldorf Astoria", "ubicacion": "Estados Unidos", "calificacion": 5, "descripcion": "Un hotel emblemático conocido por su lujo y su historia.", "capacidad_maxima_por_habitacion": 2, "area_m2": 18000, "tarifa": 1000, "numero_pisos": 42, "tamano_habitaciones_m2": 70, "ingresos_mensuales": 38000000},
  {"_id": 23, "nombre": "The Mandarin Oriental", "ubicacion": "Tailandia", "calificacion": 5, "descripcion": "Conocido por su servicio excepcional y spa de renombre mundial.", "capacidad_maxima_por_habitacion": 3, "area_m2": 20000, "tarifa": 800, "numero_pisos": 10, "tamano_habitaciones_m2": 55, "ingresos_mensuales": 30000000},
  {"_id": 24, "nombre": "Badrutt's Palace Hotel", "ubicacion": "Suiza", "calificacion": 5, "descripcion": "Hotel de lujo en los Alpes suizos, famoso por su ambiente acogedor.", "capacidad_maxima_por_habitacion": 2, "area_m2": 12000, "tarifa": 1100, "numero_pisos": 5, "tamano_habitaciones_m2": 50, "ingresos_mensuales": 28000000},
  {"_id": 25, "nombre": "The Bel Air Hotel", "ubicacion": "Estados Unidos", "calificacion": 5, "descripcion": "Rodeado de jardines exuberantes, es un refugio de lujo en la ciudad.", "capacidad_maxima_por_habitacion": 2, "area_m2": 13000, "tarifa": 950, "numero_pisos": 3, "tamano_habitaciones_m2": 55, "ingresos_mensuales": 31000000},
  {"_id": 26, "nombre": "The Fairmont", "ubicacion": "Estados Unidos", "calificacion": 5, "descripcion": "Un hotel histórico con impresionantes vistas de la ciudad y el puente Golden Gate.", "capacidad_maxima_por_habitacion": 2, "area_m2": 16000, "tarifa": 700, "numero_pisos": 6, "tamano_habitaciones_m2": 50, "ingresos_mensuales": 29000000},
  {"_id": 27, "nombre": "The Connaught", "ubicacion": "Reino Unido", "calificacion": 5, "descripcion": "Conocido por su elegancia y su servicio de mayordomo personal.", "capacidad_maxima_por_habitacion": 2, "area_m2": 14000, "tarifa": 1200, "numero_pisos": 5, "tamano_habitaciones_m2": 60, "ingresos_mensuales": 40000000},
  {"_id": 28, "nombre": "Hotel Villa Honegg", "ubicacion": "Suiza", "calificacion": 5, "descripcion": "Un hotel boutique de lujo con vistas al lago y spa.", "capacidad_maxima_por_habitacion": 2, "area_m2": 8000, "tarifa": 1000, "numero_pisos": 3, "tamano_habitaciones_m2": 40, "ingresos_mensuales": 20000000},
  {"_id": 29, "nombre": "The Sukhothai", "ubicacion": "Tailandia", "calificacion": 5, "descripcion": "Famoso por su diseño sereno y su ambiente relajante.", "capacidad_maxima_por_habitacion": 2, "area_m2": 19000, "tarifa": 850, "numero_pisos": 8, "tamano_habitaciones_m2": 55, "ingresos_mensuales": 30000000},
  {"_id": 30, "nombre": "Bulgari Hotel", "ubicacion": "Reino Unido", "calificacion": 5, "descripcion": "Un hotel de lujo que combina la elegancia de Bulgari con un estilo moderno.", "capacidad_maxima_por_habitacion": 2, "area_m2": 15000, "tarifa": 1200, "numero_pisos": 5, "tamano_habitaciones_m2": 65, "ingresos_mensuales": 42000000},
  {"_id": 31, "nombre": "Park Hyatt", "ubicacion": "Australia", "calificacion": 5, "descripcion": "Hotel contemporáneo con vistas al puerto de Sídney y el Opera House.", "capacidad_maxima_por_habitacion": 3, "area_m2": 17000, "tarifa": 900, "numero_pisos": 7, "tamano_habitaciones_m2": 55, "ingresos_mensuales": 35000000},
  {"_id": 32, "nombre": "The Shard", "ubicacion": "Reino Unido", "calificacion": 5, "descripcion": "Hotel de lujo en el edificio más alto de Europa, con vistas impresionantes.", "capacidad_maxima_por_habitacion": 2, "area_m2": 20000, "tarifa": 1300, "numero_pisos": 8, "tamano_habitaciones_m2": 70, "ingresos_mensuales": 45000000},
  {"_id": 33, "nombre": "The Mezzatorre", "ubicacion": "Italia", "calificacion": 5, "descripcion": "Ubicado en una antigua torre de vigilancia con vistas al mar.", "capacidad_maxima_por_habitacion": 2, "area_m2": 10000, "tarifa": 900, "numero_pisos": 4, "tamano_habitaciones_m2": 50, "ingresos_mensuales": 25000000},
  {"_id": 34, "nombre": "The Chedi", "ubicacion": "Omán", "calificacion": 5, "descripcion": "Un resort de lujo con un ambiente tranquilo y vistas al desierto.", "capacidad_maxima_por_habitacion": 2, "area_m2": 22000, "tarifa": 800, "numero_pisos": 4, "tamano_habitaciones_m2": 60, "ingresos_mensuales": 27000000},
  {"_id": 35, "nombre": "The Peninsula", "ubicacion": "Francia", "calificacion": 5, "descripcion": "Conocido por su servicio excepcional y su ubicación privilegiada.", "capacidad_maxima_por_habitacion": 2, "area_m2": 18000, "tarifa": 1100, "numero_pisos": 5, "tamano_habitaciones_m2": 65, "ingresos_mensuales": 39000000},
  {"_id": 36, "nombre": "St. Regis Bali", "ubicacion": "Indonesia", "calificacion": 5, "descripcion": "Hotel de lujo en la playa, conocido por su servicio y spa de renombre.", "capacidad_maxima_por_habitacion": 2, "area_m2": 20000, "tarifa": 1000, "numero_pisos": 3, "tamano_habitaciones_m2": 70, "ingresos_mensuales": 33000000},
  {"_id": 37, "nombre": "Almaza Bay", "ubicacion": "Egipto", "calificacion": 5, "descripcion": "Un lujoso resort en la costa del Mediterráneo con acceso a la playa.", "capacidad_maxima_por_habitacion": 2, "area_m2": 12000, "tarifa": 950, "numero_pisos": 4, "tamano_habitaciones_m2": 50, "ingresos_mensuales": 29000000},
  {"_id": 38, "nombre": "Aman Tokyo", "ubicacion": "Japón", "calificacion": 5, "descripcion": "Un oasis de tranquilidad en el bullicioso centro de Tokio.", "capacidad_maxima_por_habitacion": 2, "area_m2": 15000, "tarifa": 1200, "numero_pisos": 8, "tamano_habitaciones_m2": 65, "ingresos_mensuales": 36000000},
  {"_id": 39, "nombre": "The Ritz-Carlton", "ubicacion": "Hong Kong", "calificacion": 5, "descripcion": "Un hotel de lujo con impresionantes vistas de la ciudad y el puerto.", "capacidad_maxima_por_habitacion": 2, "area_m2": 20000, "tarifa": 1300, "numero_pisos": 9, "tamano_habitaciones_m2": 80, "ingresos_mensuales": 40000000},
  {"_id": 40, "nombre": "The Oberoi", "ubicacion": "India", "calificacion": 5, "descripcion": "Conocido por su servicio excepcional y vistas al mar Arábigo.", "capacidad_maxima_por_habitacion": 2, "area_m2": 18000, "tarifa": 1000, "numero_pisos": 5, "tamano_habitaciones_m2": 60, "ingresos_mensuales": 33000000}
]);

db.hoteles.find({ "nombre": { "$eq": "Pestana CR7 Gran Vía" } })
db.hoteles.find({ "calificacion": { "$gt": 4 } })
db.hoteles.find({ "tarifa": { "$gte": 1000 } })
db.hoteles.find({ "area_m2": { "$lt": 15000 } })
db.hoteles.find({ "capacidad_maxima_por_habitacion": { "$lte": 2 } })
db.hoteles.find({ "ubicacion": { "$ne": "Estados Unidos" } })
db.hoteles.find({ "ingresos_mensuales": { "$in": [20000000, 25000000, 30000000] } })
db.hoteles.find({ "ingresos_mensuales": { "$nin": [25000000, 30000000, 35000000] } })
db.hoteles.find()
db.hoteles.deleteOne({ "nombre": "Burj Al Arab" })